.flowzone:
  - &downloadSourceArtifact
    name: Download source artifact
    uses: actions/download-artifact@v3
    with:
      name: source-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
      path: ${{ runner.temp }}

  - &extractSourceArtifact
    name: Extract source artifact
    # tar: Cannot connect to D: resolve failed
    shell: pwsh
    working-directory: .
    run: tar -xvf ${{ runner.temp }}/source.tgz

name: Flowzone

# {{ ./templates/on_webhook.yml}}

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: flowzone-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_USER: "flowzone" # does not seem to matter what is used here
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN || secrets.FLOWZONE_TOKEN }}
  NPM_REGISTRY: registry.npmjs.org

jobs:
  ###################################################
  ## event types
  ###################################################

  event_types:
    # {{ ./templates/event_types.yml}}

  ###################################################
  ## project types
  ###################################################

  project_types:
    # {{ ./templates/project_types.yml}}

  ###################################################
  ## versioned source
  ###################################################

  versioned_source:
    # {{ ./templates/versioned_source.yml}}

  ###################################################
  ## npm
  ###################################################

  npm_test:
    # {{ ./templates/npm_test.yml}}

  npm_publish:
    # {{ ./templates/npm_publish.yml}}

  npm_finalize:
    # {{ ./templates/npm_finalize.yml}}

  npm_docs_finalize:
    # {{ ./templates/npm_docs_finalize.yml}}

  ###################################################
  ## docker
  ###################################################

  docker_test:
    # {{ ./templates/docker_test.yml}}

  docker_publish:
    # {{ ./templates/docker_publish.yml}}

  docker_finalize:
    # {{ ./templates/docker_finalize.yml}}

  ###################################################
  ## balena
  ###################################################

  balena_publish:
    # {{ ./templates/balena_publish.yml}}

  balena_finalize:
    # {{ ./templates/balena_finalize.yml}}

  ###################################################
  ## Python
  ###################################################

  python_test:
    # {{ ./templates/python_test.yml}}

  ###################################################
  ## custom
  ###################################################

  custom_test:
    # {{ ./templates/custom_test.yml}}

  custom_publish:
    # {{ ./templates/custom_publish.yml}}

  custom_finalize:
    # {{ ./templates/custom_finalize.yml}}

  custom_clean:
    # {{ ./templates/custom_clean.yml}}

  custom_always:
    # {{ ./templates/custom_always.yml}}

  ###################################################
  ## protect branch
  ###################################################

  # ... or use GiHub CLI instead of cURL: https://cli.github.com/manual/gh_release
  # https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
  protect_branch:
    # {{ ./templates/protect_branch.yml}}
