name: "secrets test"

on:
  workflow_call:
    secrets:
      FLOWZONE_TOKEN:
        description: "Personal access token (PAT) for the GitHub service account with admin/owner permissions"
        required: true
      COMPOSE_VARS:
        description: "The compose vars to check for leaked secrets"
        required: true
    inputs:
      run_id: 
        description: "The run ID to check for leaked secrets"
        required: true
        type: string

jobs:
  secrets_check:
    name: Secrets test
    runs-on: ubuntu-22.04

    steps:
      - name: Check for leaked secrets
        env:
          GH_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
          GH_PROMPT_DISABLED: "true"
          GH_DEBUG: "true"
          GH_PAGER: "cat"
          GH_REPO: ${{ github.repository }}
        run: |
          echo "${{ secrets.COMPOSE_VARS }}" | base64 --decode > .env
        
          jobs="$(gh run view ${{ inputs.run_id }} --json=jobs --jq '.jobs[].databaseId')"

          for job in ${jobs}
          do
            gh run view --job="${job}" --log > "${job}.log"

            while read -r line
            do
              secret="$(echo "${line}" | awk -F'=' '{print $2}')"
              if grep -q "${secret}" "${job}.log"
              then
                echo "::error::Found leaked secret from COMPOSE_VARS in job ${job}"
                gh run view --job="${job}"
                exit 1
              fi
            done < .env
          done

          
