name: Tests

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: ./.github/workflows/flowzone.yml
    secrets: inherit
    with:
      working_directory: ./tests
      repo_config: true
      repo_description: "Reusable, opinionated, zero-conf workflows for GitHub actions"
      docker_images: |
        ghcr.io/product-os/flowzone
      balena_slugs: |
        product_os/flowzone
      cargo_targets: |
        x86_64-unknown-linux-gnu,
        armv7-unknown-linux-gnueabi,
        aarch64-unknown-linux-gnu
      cloudflare_website: "flowzone"
      bake_targets: default,multiarch

  secrets:
    name: Secrets
    uses: ./.github/workflows/secrets.yml
    secrets: inherit
    needs:
      - flowzone
    with:
      run_id: ${{ github.run_id }}

  e2e:
    name: e2e
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
    needs:
      - flowzone
      - secrets
